name: advanced_firebase_logger_example
description: "Example app demonstrating the advanced_firebase_logger package"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.2.0
  firebase_core: ^4.6.0
  advanced_firebase_logger:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
