name: advanced_firebase_logger
description: "An advanced Flutter package for logging to Firebase Cloud Firestore with multiple log levels, rich metadata support, and customizable features."
version: 0.1.1
homepage: https://github.com/orkundayi/advanced_firebase_logger
repository: https://github.com/orkundayi/advanced_firebase_logger

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
